#!/bin/sh

## Make symbolic links to folders containing other wordlists
[ -d /usr/share/dirb/wordlists ] \
  && ln -sf /usr/share/dirb/wordlists /usr/share/wordlists/dirb

[ -d /usr/share/dirbuster/wordlists ] \
  && ln -sf /usr/share/dirbuster/wordlists /usr/share/wordlists/dirbuster

[ -d /usr/share/fern-wifi-cracker/extras/wordlists ] \
  && ln -sf /usr/share/fern-wifi-cracker/extras/wordlists /usr/share/wordlists/fern-wifi

[ -d /usr/share/metasploit-framework/data/wordlists ] \
  && ln -sf /usr/share/metasploit-framework/data/wordlists /usr/share/wordlists/metasploit

[ -d /opt/metasploit/apps/pro/data/wordlists ] \
  && ln -sf /opt/metasploit/apps/pro/data/wordlists /usr/share/wordlists/metasploit-pro

[ -d /usr/share/wfuzz/wordlist ] \
  && ln -sf /usr/share/wfuzz/wordlist /usr/share/wordlists/wfuzz

[ -d /usr/share/seclists ] \
  && ln -sf /usr/share/seclists /usr/share/wordlists/seclists

[ -d /usr/share/legion/wordlists ] \
  && ln -sf /usr/share/legion/wordlists /usr/share/wordlists/legion

[ -d /usr/share/amass/wordlists ] \
  && ln -sf /usr/share/amass/wordlists /usr/share/wordlists/amass

[ -d /usr/share/brutespray/wordlist ] \
  && ln -sf /usr/share/brutespray/wordlist /usr/share/wordlists/brutespray


# Make symbolic links to individual files
[ -e /usr/share/sqlmap/data/txt/wordlist.tx_ ] \
  && unzip -o -d /usr/share/sqlmap/data/txt/ /usr/share/sqlmap/data/txt/wordlist.tx_ 2>0 \
  && ln -sf /usr/share/sqlmap/data/txt/wordlist.txt /usr/share/wordlists/sqlmap.txt

[ -e /usr/share/dnsmap/wordlist_TLAs.txt ] \
  && ln -sf /usr/share/dnsmap/wordlist_TLAs.txt /usr/share/wordlists/dnsmap.txt

[ -e /usr/share/nmap/nselib/data/passwords.lst ] \
  && ln -sf /usr/share/nmap/nselib/data/passwords.lst /usr/share/wordlists/nmap.lst

[ -e /usr/share/set/src/fasttrack/wordlist.txt ] \
  && ln -sf /usr/share/set/src/fasttrack/wordlist.txt /usr/share/wordlists/fasttrack.txt

[ -e /usr/share/john/password.lst ] \
  && ln -sf /usr/share/john/password.lst /usr/share/wordlists/john.lst

[ -e /usr/share/dict/wordlist-probable.txt ] \
  && ln -sf /usr/share/dict/wordlist-probable.txt /usr/share/wordlists/wifite.txt

exit 0
