#!/bin/sh

## Remove the directory symlinks made by postinst
[ -h /usr/share/wordlists/dirb ] \
  && rm -f /usr/share/wordlists/dirb

[ -h /usr/share/wordlists/dirbuster ] \
  && rm -f /usr/share/wordlists/dirbuster

[ -h /usr/share/wordlists/fern-wifi ] \
  && rm -f /usr/share/wordlists/fern-wifi

[ -h /usr/share/wordlists/metasploit ] \
  && rm -f /usr/share/wordlists/metasploit

[ -h /usr/share/wordlists/metasploit-pro ] \
  && rm -f /usr/share/wordlists/metasploit-pro

[ -h /usr/share/wordlists/wfuzz ] \
  && rm -f /usr/share/wordlists/wfuzz

[ -h /usr/share/wordlists/seclists ] \
  && rm -f /usr/share/wordlists/seclists

[ -h /usr/share/wordlists/legion ] \
  && rm -f /usr/share/wordlists/legion

[ -h /usr/share/wordlists/amass ] \
  && rm -f /usr/share/wordlists/amass

[ -h /usr/share/wordlists/brutespray ] \
  && rm -f /usr/share/wordlists/brutespray
  

## Remove the file symlinks made by postinst
[ -h /usr/share/wordlists/sqlmap.txt ] \
  && rm -f /usr/share/wordlists/sqlmap.txt

[ -h /usr/share/wordlists/dnsmap.txt ] \
  && rm -f /usr/share/wordlists/dnsmap.txt

[ -h /usr/share/wordlists/nmap.lst ] \
  && rm -f /usr/share/wordlists/nmap.lst

[ -h /usr/share/wordlists/fasttrack.txt ] \
  && rm -f /usr/share/wordlists/fasttrack.txt

[ -h /usr/share/wordlists/john.lst ] \
  && rm -f /usr/share/wordlists/john.lst

[ -h /usr/share/wordlists/wifite.txt ] \
  && rm -f /usr/share/wordlists/wifite.txt

# Remove extracted rockyou.txt
[ "$1" = "remove" ] \
  && rm -f /usr/share/wordlists/rockyou.txt

exit 0
