#!/bin/bash

# Remove the directory symlinks made by postinst

if [ -e /usr/share/wordlists/dirb ]; then rm -rf /usr/share/wordlists/dirb; fi
if [ -e /usr/share/wordlists/dirbuster ]; then rm -rf /usr/share/wordlists/dirbuster; fi
if [ -e /usr/share/wordlists/fern-wifi ]; then rm -rf /usr/share/wordlists/fern-wifi; fi
if [ -e /usr/share/wordlists/metasploit-jtr ]; then rm -rf /usr/share/wordlists/metasploit-jtr; fi
if [ -e /usr/share/wordlists/metasploit ]; then rm -rf /usr/share/wordlists/metasploit; fi
if [ -e /usr/share/wordlists/metasploit-pro ]; then rm -rf /usr/share/wordlists/metasploit-pro; fi
if [ -e /usr/share/wordlists/webslayer ]; then rm -rf /usr/share/wordlists/webslayer; fi
if [ -e /usr/share/wordlists/wfuzz ]; then rm -rf /usr/share/wordlists/wfuzz; fi
if [ -e /usr/share/wordlists/seclists ]; then rm -rf /usr/share/wordlists/seclists; fi

# Remove the file symlinks made by postinst

if [ -e /usr/share/wordlists/sqlmap.txt ]; then rm -rf /usr/share/wordlists/sqlmap.txt; fi
if [ -e /usr/share/wordlists/dnsmap.txt ]; then rm -rf /usr/share/wordlists/dnsmap.txt; fi
if [ -e /usr/share/wordlists/wfuzz.txt ]; then rm -rf /usr/share/wordlists/wfuzz.txt; fi
if [ -e /usr/share/wordlists/nmap.lst ]; then rm -rf /usr/share/wordlists/nmap.lst; fi
if [ -e /usr/share/wordlists/fasttrack.txt ]; then rm -rf /usr/share/wordlists/fasttrack.txt; fi
if [ -e /usr/share/wordlists/termineter.txt ]; then rm -rf /usr/share/wordlists/termineter.txt; fi
if [ -e /usr/share/wordlists/w3af.txt ]; then rm -rf /usr/share/wordlists/w3af.txt; fi
if [ -e /usr/share/wordlists/wpscan.txt ]; then rm -rf /usr/share/wordlists/wpscan.txt; fi
