Document: wordlists
Title: Debian wordlists Manual
Author: <insert document author here>
Abstract: This manual describes what wordlists is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wordlists/wordlists.sgml.gz

Format: postscript
Files: /usr/share/doc/wordlists/wordlists.ps.gz

Format: text
Files: /usr/share/doc/wordlists/wordlists.text.gz

Format: HTML
Index: /usr/share/doc/wordlists/html/index.html
Files: /usr/share/doc/wordlists/html/*.html
